// <auto-generated />
namespace P2BUltimate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _14122022 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_14122022));
        
        string IMigrationMetadata.Id
        {
            get { return "202212140541323_14-12-2022"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
